---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.69.57
    jenkins-agent-01:
      ansible_host: 84.201.152.192
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: joos