---
- name: Install Nginx for logs
  hosts: lighthouse, vector
  roles:
    - nginx-role
    
####################################################################################
- name: Install Lighthouse
  hosts: lighthouse
  pre_tasks:
    - name: Lighthouse | Install dependencies
      become: true
      ansible.builtin.yum:
        name: git
        state: present
      tags: git-install
  roles:
    - lighthouse-role

####################################################################################################################################################
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse-role

################################################################################################################################################
- name: Install Vector
  hosts: vector
  roles:
    - vector-role
